=begin
#WhatsAPI Go

#The V2 of WhatsAPI Go

The version of the OpenAPI document: 2.0
Contact: manjit@sponsorbook.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::InstanceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InstanceApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::InstanceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InstanceApi' do
    it 'should create an instance of InstanceApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::InstanceApi)
    end
  end

  # unit tests for instances_create_get
  # Creates a new instance key.
  # This endpoint is used to create a new WhatsApp Web instance.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :instance_key Insert instance key if you want to provide custom key
  # @return [MainAPIResponse]
  describe 'instances_create_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for instances_instance_key_contacts_get
  # Get contacts.
  # Fetches the list of contacts in the instance.
  # @param instance_key Instance key
  # @param [Hash] opts the optional parameters
  # @return [MainAPIResponse]
  describe 'instances_instance_key_contacts_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for instances_instance_key_delete_delete
  # Delete Instance.
  # Deletes the instance with the provided key.
  # @param instance_key Instance key
  # @param [Hash] opts the optional parameters
  # @return [MainAPIResponse]
  describe 'instances_instance_key_delete_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for instances_instance_key_get
  # Get Instance.
  # Returns the instance data of single instance with connection status.
  # @param instance_key Instance key
  # @param [Hash] opts the optional parameters
  # @return [MainAPIResponse]
  describe 'instances_instance_key_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for instances_instance_key_logout_delete
  # Logout Instance.
  # Logouts of the instance with the provided key.
  # @param instance_key Instance key
  # @param [Hash] opts the optional parameters
  # @return [MainAPIResponse]
  describe 'instances_instance_key_logout_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for instances_instance_key_qrcode_get
  # Get QrCode.
  # Returns the qrcode in the base64 format.
  # @param instance_key Instance key
  # @param [Hash] opts the optional parameters
  # @return [MainAPIResponse]
  describe 'instances_instance_key_qrcode_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for instances_instance_key_webhook_put
  # Change Webhook url.
  # Changes the webhook url of an instance.
  # @param instance_key Instance key
  # @param data Message data
  # @param [Hash] opts the optional parameters
  # @return [MainAPIResponse]
  describe 'instances_instance_key_webhook_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for instances_list_get
  # Get all instances.
  # Fetches the list of all Instances with login status.
  # @param [Hash] opts the optional parameters
  # @return [MainAPIResponse]
  describe 'instances_list_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
