=begin
#WhatsAPI Go

#The V2 of WhatsAPI Go

The version of the OpenAPI document: 2.0
Contact: manjit@sponsorbook.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::MiscellaneousApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MiscellaneousApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::MiscellaneousApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MiscellaneousApi' do
    it 'should create an instance of MiscellaneousApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::MiscellaneousApi)
    end
  end

  # unit tests for instances_instance_key_misc_profile_pic_get
  # Get profile pic.
  # Returns the profile pic of the given user.
  # @param instance_key Instance key
  # @param jid JID
  # @param [Hash] opts the optional parameters
  # @return [MainAPIResponse]
  describe 'instances_instance_key_misc_profile_pic_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for instances_instance_key_misc_user_info_post
  # Fetches the users info.
  # Gets the user info for the given user ids. This does not checks if user is registered or not
  # @param instance_key Instance key
  # @param data Data
  # @param [Hash] opts the optional parameters
  # @return [MainAPIResponse]
  describe 'instances_instance_key_misc_user_info_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
