=begin
#WhatsAPI Go

#The V2 of WhatsAPI Go

The version of the OpenAPI document: 2.0
Contact: manjit@sponsorbook.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::StructsGroupUpdateNamePayload
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::StructsGroupUpdateNamePayload do
  let(:instance) { OpenapiClient::StructsGroupUpdateNamePayload.new }

  describe 'test an instance of StructsGroupUpdateNamePayload' do
    it 'should create an instance of StructsGroupUpdateNamePayload' do
      expect(instance).to be_instance_of(OpenapiClient::StructsGroupUpdateNamePayload)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
