=begin
#WhatsAPI Go

#The V2 of WhatsAPI Go

The version of the OpenAPI document: 2.0
Contact: manjit@sponsorbook.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/instances_instance_key_groups_group_id_profile_pic_put_request'
require 'openapi_client/models/instances_instance_key_send_audio_post_request'
require 'openapi_client/models/instances_instance_key_send_document_post_request'
require 'openapi_client/models/instances_instance_key_send_image_post_request'
require 'openapi_client/models/instances_instance_key_send_upload_post_request'
require 'openapi_client/models/instances_instance_key_send_video_post_request'
require 'openapi_client/models/main_api_response'
require 'openapi_client/models/structs_button_message_payload'
require 'openapi_client/models/structs_button_message_with_media_payload'
require 'openapi_client/models/structs_contact_message_payload'
require 'openapi_client/models/structs_contact_message_payload_vcard'
require 'openapi_client/models/structs_file_upload'
require 'openapi_client/models/structs_group_create_payload'
require 'openapi_client/models/structs_group_update_description_payload'
require 'openapi_client/models/structs_group_update_name_payload'
require 'openapi_client/models/structs_group_update_participants_payload'
require 'openapi_client/models/structs_list_item'
require 'openapi_client/models/structs_list_message_payload'
require 'openapi_client/models/structs_list_section'
require 'openapi_client/models/structs_location_message_payload'
require 'openapi_client/models/structs_location_message_payload_location'
require 'openapi_client/models/structs_poll_message_payload'
require 'openapi_client/models/structs_reply_button'
require 'openapi_client/models/structs_send_media_payload'
require 'openapi_client/models/structs_template_button'
require 'openapi_client/models/structs_template_button_payload'
require 'openapi_client/models/structs_template_button_with_media_payload'
require 'openapi_client/models/structs_text_message'
require 'openapi_client/models/structs_user_info_payload'
require 'openapi_client/models/structs_webhook_payload'

# APIs
require 'openapi_client/api/group_management_api'
require 'openapi_client/api/instance_api'
require 'openapi_client/api/message_sending_api'
require 'openapi_client/api/miscellaneous_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
