=begin
#WhatsAPI Go

#The V2 of WhatsAPI Go

The version of the OpenAPI document: 2.0
Contact: manjit@sponsorbook.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/api_response'
require 'openapi_client/models/button_message_payload'
require 'openapi_client/models/button_message_with_media_payload'
require 'openapi_client/models/contact_message_payload'
require 'openapi_client/models/contact_message_payload_vcard'
require 'openapi_client/models/file_upload'
require 'openapi_client/models/group_create_payload'
require 'openapi_client/models/group_update_description_payload'
require 'openapi_client/models/group_update_name_payload'
require 'openapi_client/models/group_update_participants_payload'
require 'openapi_client/models/list_item'
require 'openapi_client/models/list_message_payload'
require 'openapi_client/models/list_section'
require 'openapi_client/models/location_message_payload'
require 'openapi_client/models/location_message_payload_location'
require 'openapi_client/models/poll_message_payload'
require 'openapi_client/models/reply_button'
require 'openapi_client/models/send_audio_request'
require 'openapi_client/models/send_document_request'
require 'openapi_client/models/send_image_request'
require 'openapi_client/models/send_media_payload'
require 'openapi_client/models/send_video_request'
require 'openapi_client/models/set_group_picture_request'
require 'openapi_client/models/template_button'
require 'openapi_client/models/template_button_payload'
require 'openapi_client/models/template_button_with_media_payload'
require 'openapi_client/models/text_message'
require 'openapi_client/models/upload_media_request'
require 'openapi_client/models/user_info_payload'
require 'openapi_client/models/webhook_payload'

# APIs
require 'openapi_client/api/business_management_api'
require 'openapi_client/api/group_management_api'
require 'openapi_client/api/instance_api'
require 'openapi_client/api/message_sending_api'
require 'openapi_client/api/miscellaneous_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
